### ISSUE TITLE
couldn't find it in the cached files and it looks like microsoft/Florence-2-base-ft is not the path to a directory containing a file named configuration_florence2.py.

### ISSUE THREAD

**Issue by ccartermices** [miaoshouai/ComfyUI-Miaoshouai-Tagger#13]
How to fix it?

Error occurred when executing Miaoshouai_Tagger:

We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like microsoft/Florence-2-base-ft is not the path to a directory containing a file named configuration_florence2.py.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

File "F:\quark_download\ComfyUI-aki\ComfyUI-aki-v1.3\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\quark_download\ComfyUI-aki\ComfyUI-aki-v1.3\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\quark_download\ComfyUI-aki\ComfyUI-aki-v1.3\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\quark_download\ComfyUI-aki\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 136, in start_tag
model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation=attention, device_map=device,
File "F:\quark_download\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\models\auto\auto_factory.py", line 521, in from_pretrained
config, kwargs = AutoConfig.from_pretrained(
File "F:\quark_download\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1120, in from_pretrained
config_class = get_class_from_dynamic_module(
File "F:\quark_download\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\dynamic_module_utils.py", line 488, in get_class_from_dynamic_module
final_module = get_cached_module_file(
File "F:\quark_download\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\dynamic_module_utils.py", line 293, in get_cached_module_file
resolved_module_file = cached_file(
File "F:\quark_download\ComfyUI-aki\ComfyUI-aki-v1.3\python\lib\site-packages\transformers\utils\hub.py", line 441, in cached_file
raise EnvironmentError(

**Comment by miaoshouai** [comment]
if auto download fail for connection problems, you can gitclone the model under the models\LLM folder in your comfyui
eg: git clone https://huggingface.co/MiaoshouAI/Florence-2-base-PromptGen-v1.5

This will do the something as auto download

**Comment by ccartermices** [comment]
I have gitted clone them but the error still existed.

**Comment by miaoshouai** [comment]
still says  microsoft/Florence-2-base-ft  is not the path to a directory？ 
that is the wrong model to start with.

**Comment by ccartermices** [comment]
I really use to gitclone (git clone https://hf-mirror.com/MiaoshouAI/Florence-2-base-PromptGen-v1.5.git) the promtgen model, here are the content in my folder.
![Uploading U@C[{Y{VUY}SG$J68MD14C5.png…]()

**Comment by ccartermices** [comment]
I really use to gitclone (git clone https://hf-mirror.com/MiaoshouAI/Florence-2-base-PromptGen-v1.5.git) the promtgen model, here are the content in my folder.
![U@C {Y{VUY}SG$J68MD14C5](https://github.com/user-attachments/assets/45fff49c-2c5b-45fe-abdb-dc37d05ba912)

**Comment by miaoshouai** [comment]
try update your comfyui version and also make sure tagger is updated to the new version

**Comment by ccartermices** [comment]
I updated the comfyui version but it still has this error.

**Comment by ccartermices** [comment]
I even gitclone florence large and base into LLM filefold but it still has this error. Any other way to detect cause of this error?

**Comment by Yuliucheng** [comment]
你的网络有问题, 我在云端也遇到了, 改一下config文件就好 ,或者你直接把我改好的文件全部覆盖到模型就好了:https://drive.google.com/drive/folders/1gnAFrQQftnYPsmUu4JUNyG8VehYCDqvx?usp=drive_link

**Comment by miaoshouai** [comment]
> I really use to gitclone (git clone https://hf-mirror.com/MiaoshouAI/Florence-2-base-PromptGen-v1.5.git) the promtgen model, here are the content in my folder. ![U@C {Y{VUY}SG$J68MD14C5](https://private-user-images.githubusercontent.com/39996331/365933891-45fff49c-2c5b-45fe-abdb-dc37d05ba912.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNzg2NzAsIm5iZiI6MTcyNjA3ODM3MCwicGF0aCI6Ii8zOTk5NjMzMS8zNjU5MzM4OTEtNDVmZmY0OWMtMmM1Yi00NWZlLWFiZGItZGMzN2QwNWJhOTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE4MTI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YTBjMzNiNTdmZWQzYjRmYmRkZmVjOGVmNWVkZDQwZTRhNDdmZjRiMDk1ZTUzMGZhMzA4NjQ5N2QyNzA1YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m_VR1pHSBLC3R47EASudXWB3aOWrulg38x-Ga4O2w74)

try download the model from the baidu drive if you are in Mainland China: https://resource.miaoshouai.com/1156.html

**Comment by ccartermices** [comment]
> 你的网络有问题, 我在云端也遇到了, 改一下config文件就好 ,或者你直接把我改好的文件全部覆盖到模型就好了:https://drive.google.com/drive/folders/1gnAFrQQftnYPsmUu4JUNyG8VehYCDqvx?usp=drive_link

我下载了这些config但是报错了：No module named 'transformers_modules.Florence-2-base-PromptGen-v1且在这些文件中没有找到-v1的字样

**Comment by Yuliucheng** [comment]
> > 你的网络有问题, 我在云端也遇到了, 改一下config文件就好 ,或者你直接把我改好的文件全部覆盖到模型就好了:https://drive.google.com/drive/folders/1gnAFrQQftnYPsmUu4JUNyG8VehYCDqvx?usp=drive_link
> 
> 我下载了这些config但是报错了：No module named 'transformers_modules.Florence-2-base-PromptGen-v1且在这些文件中没有找到-v1的字样

你这报错有点诡异,我无法复现, 因为我只是把config文件开头的"_name_or_path"和"auto_map"改成原版Florence2的名称并且上传了三个需要联网下载的py文件, 并没有修改插件或模型的的导入transformer模块的代码, 有可能已经不是模型文件缺失的问题了, 可以检查下transformers版本, 也许有用?

**Comment by ccartermices** [comment]
谢谢各位大佬的建议，已经解决了
