### ISSUE TITLE
Error When Using Florence-2-large-PromptGen-v15 Model in Florence Node

### ISSUE THREAD

**Issue by camoody1** [miaoshouai/ComfyUI-Miaoshouai-Tagger#19]
I am able to use both the Florence-2-base-PromptGen-v15 and Florence-2-large-PromptGen-v15 models with your Tagger node, but when I try to use either of them with the Florence2Run node, I get the following error:

`ValueError: The checkpoint you are trying to load has model type `florence2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.`

Any idea how I can fix this? I'm fairly certain that I'm running the most up-to-date version of Transformers.

**Comment by miaoshouai** [comment]
likely because the config setting used in florence2run is different

**Comment by Latentnaut** [comment]
I've got the same error.

By the way, I copied the model to this location: C:\AI\ComfyUI_windows_portable\ComfyUI\LLM

And that's the route I've pasted in the node, is it correct?

![image](https://github.com/user-attachments/assets/f0b7c40f-c07b-4b0e-ba54-767c4ddf9507)

**Comment by camoody1** [comment]
I'm getting this same error in my Comfy log even when I'm using your node. Your node lets me still complete the action, but the Florence2Run node does not. Not sure what this error means or if you can fix it.

![image](https://github.com/user-attachments/assets/ddce8ce8-c242-4822-9ef1-b2bd0b350ca6)

**Comment by miaoshouai** [comment]
refer to this issue for the fix solusion: https://github.com/miaoshouai/ComfyUI-Miaoshouai-Tagger/issues/23#issuecomment-2401340644
