### ISSUE TITLE
Bug: Promptgen-large-v1.5 Fails Unless I Run The Base Model First

### ISSUE THREAD

**Issue by camoody1** [miaoshouai/ComfyUI-Miaoshouai-Tagger#20]
When using your MiashouAI Tagger node, I get an error message when using the promptgen-large-v15 model UNLESS I first use the base model. Here is the error:

![image](https://github.com/user-attachments/assets/45ce7590-a42f-451b-b591-4255ae4a037e)

## Additional Context
After this error, if I switch to the base model and run the tagger, I get a successful run. THEN, I can change to the large model and it will complete successfully, too. Super weird issue.

**Comment by camoody1** [comment]
I see in your nodes.py file, there is a piece of code that reads:
`if model == 'promptgen_large_v1.5':`

However, the name of the model in the node droplist is actually "promptgen_large_v15" (there is no period between the 1 and 5). Could this be the issue?

**Comment by miaoshouai** [comment]
update the node to fix this problem

**Comment by camoody1** [comment]
I have updated the node and now I'm getting a different error message. I cannot run the large model from within your node at all, now.
![image](https://github.com/user-attachments/assets/889eb4e8-8b49-4eaa-a9f5-1358ae6ef99b)

I can still use your base model, but the large isn't working. 🤷🏼

**Comment by miaoshouai** [comment]
rename your models\LLM\Florence-2-large-PromptGen-v1.5\florence-2-large to florence2_large

**Comment by camoody1** [comment]
A new error for the large model:
```
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger\nodes.py", line 148, in start_tag
    from florence2_large_ft.modeling_florence2 import Florence2ForConditionalGeneration
ModuleNotFoundError: No module named 'florence2_large_ft'
```
If I go to lines 148 and 149 in nodes.py, you have:
```
from florence2_large_ft.modeling_florence2 import Florence2ForConditionalGeneration
from florence2_large_ft.configuration_florence2 import Florence2Config
```
If I change these lines to the following, the large model works:
```
from florence2_large.modeling_florence2 import Florence2ForConditionalGeneration
from florence2_large.configuration_florence2 import Florence2Config
```

**Comment by miaoshouai** [comment]
refer to this issue for the fix solusion: https://github.com/miaoshouai/ComfyUI-Miaoshouai-Tagger/issues/23#issuecomment-2401340644
