### ISSUE TITLE
Miaoshouai_Tagger No module named 'florence2_base_ft'

### ISSUE THREAD

**Issue by AdamSmithIsHere** [miaoshouai/ComfyUI-Miaoshouai-Tagger#21]
我也是遇到了同样的问题。
选择"promptgen_large_v1.5"就会出错“Miaoshouai_Tagger No module named 'florence2_base_ft'”，而选择“promptgen_base_v1.5”就没有问题。
“C:\ComfyUI_windows_portable\ComfyUI\models\LLM\Florence-2-base-PromptGen-v1.5\florence2_base_ft”这个目录是存在的，下面有4个florence2.py结尾的文件。

不知道是什么情况，莫名其妙的。

我发到这里，也是给大家一个参考。

**Comment by SagarChandra07** [comment]
maybe this will help

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by miaoshouai** [comment]
update the node to the latest should resolve this problem

**Comment by miaoshouai** [comment]
refer to this issue for the fix solusion: https://github.com/miaoshouai/ComfyUI-Miaoshouai-Tagger/issues/23#issuecomment-2401340644
