### ISSUE TITLE
也遇见此类问题

### ISSUE THREAD

**Issue by kaiday2023** [miaoshouai/ComfyUI-Miaoshouai-Tagger#24]
We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like microsoft/Florence-2-base-ft is not the path to a directory containing a file named processing_florence2.py.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by miaoshouai** [comment]
refer to this issue for the fix solusion: https://github.com/miaoshouai/ComfyUI-Miaoshouai-Tagger/issues/23#issuecomment-2401340644
