### ISSUE TITLE
Florence2 not recognized

### ISSUE THREAD

**Issue by vootox** [miaoshouai/ComfyUI-Miaoshouai-Tagger#25]
The checkpoint you are trying to load has model type `florence2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.

This suddenly started happening tonight. I upgraded transformers from 4.45.1 to 4.45.2 but still this error.

I can post the log from comfyui tomorrow (may need to remove personal details)

**Comment by wolfden** [comment]
> The checkpoint you are trying to load has model type `florence2` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
> 
> This suddenly started happening tonight. I upgraded transformers from 4.45.1 to 4.45.2 but still this error.
> 
> I can post the log from comfyui tomorrow (may need to remove personal details)

I got same thing, reverting the node.py file in ComfyUI-Miaoshouai-Tagger lets it work again, not a fix, but to get it working again

**Comment by wolfden** [comment]
> try also update the model to the latest by deleting it from the models\LLM folder and re-run it with the latest tagger version

that works for me

**Comment by vootox** [comment]
> try also update the model to the latest by deleting it from the models\LLM folder and re-run it with the latest tagger version

This also worked for me, thanks also to wolfden for other fix option.
