### ISSUE TITLE
imports.remove("flash_attn") ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by DrJKL** [miaoshouai/ComfyUI-Miaoshouai-Tagger#9]
https://github.com/miaoshouai/ComfyUI-Miaoshouai-Tagger/blob/f47ec22745fe68e6a36a3b112f3c367d5166f858/nodes.py#L19

Could you catch when there's no `flash_attn` to remove, a la https://github.com/kijai/ComfyUI-Florence2/blob/da51d4ae725126c906a4145bab93b3d6f768abbd/nodes.py#L25?

**Comment by miaoshouai** [comment]
thanks for the input. pr is merged to main
